frr defaults traditional
hostname p1
!
interface lo
 ip address 192.0.2.11/32
 ip router isis CORE
 isis passive
!
interface eth1
 ip address 10.0.0.0/31
 ip router isis CORE
 isis network point-to-point
!
interface eth2
 ip address 10.0.0.3/31
 ip router isis CORE
 isis network point-to-point
!
interface eth3
 ip address 10.0.0.7/31
 ip router isis CORE
 isis network point-to-point
!
interface eth4
 ip address 10.0.0.11/31
 ip router isis CORE
 isis network point-to-point
!
interface eth5
 ip address 10.0.0.15/31
 ip router isis CORE
 isis network point-to-point
!
interface eth6
 ip address 10.0.0.19/31
 ip router isis CORE
 isis network point-to-point
!
interface eth7
 ip address 10.0.0.23/31
 ip router isis CORE
 isis network point-to-point
!
router isis CORE
 is-type level-2-only
 set-overload-bit on-startup 90
 net 49.0001.1920.0000.2011.00
!
router bgp 65000
 bgp router-id 192.0.2.11
 neighbor 192.0.2.101 remote-as 65000
 neighbor 192.0.2.101 update-source lo
 neighbor 192.0.2.102 remote-as 65000
 neighbor 192.0.2.102 update-source lo
 address-family ipv4 unicast
  neighbor 192.0.2.101 activate
  neighbor 192.0.2.102 activate
 exit-address-family
!
