frr defaults traditional
hostname pe3
!
interface lo
 ip address 192.0.2.3/32
 ip router isis CORE
 isis passive
!
interface eth1
 ip address 10.0.0.10/31
 ip router isis CORE
 isis network point-to-point
!
interface eth2
 ip address 10.0.0.12/31
 ip router isis CORE
 isis network point-to-point
!
interface eth3
 ip address 10.1.2.0/31
!
router isis CORE
 is-type level-2-only
 set-overload-bit on-startup 90
 net 49.0001.1920.0000.2003.00
!
router bgp 65000
 bgp router-id 192.0.2.3
 no bgp ebgp-requires-policy
 neighbor 192.0.2.101 remote-as 65000
 neighbor 192.0.2.101 update-source lo
 neighbor 192.0.2.102 remote-as 65000
 neighbor 192.0.2.102 update-source lo
 neighbor 10.1.2.1 remote-as 65002
 address-family ipv4 unicast
  neighbor 192.0.2.101 next-hop-self
  neighbor 192.0.2.101 activate
  neighbor 192.0.2.102 next-hop-self
  neighbor 192.0.2.102 activate
  neighbor 10.1.2.1 activate
 exit-address-family
!
