frr defaults traditional
hostname rr2
!
interface lo
 ip address 192.0.2.102/32
 ip router isis CORE
 isis passive
!
interface eth1
 ip address 10.0.0.22/31
 ip router isis CORE
 isis network point-to-point
!
interface eth2
 ip address 10.0.0.24/31
 ip router isis CORE
 isis network point-to-point
!
router isis CORE
 is-type level-2-only
 set-overload-bit on-startup 90
 net 49.0001.1920.0000.2102.00
!
router bgp 65000
 bgp router-id 192.0.2.102
 bgp cluster-id 2.2.2.2
 neighbor RRC peer-group
 neighbor RRC remote-as 65000
 neighbor RRC update-source lo
 neighbor 192.0.2.1  peer-group RRC
 neighbor 192.0.2.2  peer-group RRC
 neighbor 192.0.2.3  peer-group RRC
 neighbor 192.0.2.4  peer-group RRC
 neighbor 192.0.2.11 peer-group RRC
 neighbor 192.0.2.12 peer-group RRC
 neighbor 192.0.2.101 remote-as 65000
 neighbor 192.0.2.101 update-source lo
 address-family ipv4 unicast
  neighbor RRC route-reflector-client
  neighbor RRC activate
  neighbor 192.0.2.101 activate
 exit-address-family
!
